name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to Dark Crafters BD bot repository! We appreciate your contribution and look forward to your first issue!"
        pr-message: "🎉 Congratulations on making your first Pull Request to the Dark Crafters BD bot repository!"
